
#[mitm]
hostname = wechatapp.ecej.com, businesshall.ecej.com

#[rewrite_local]

^https:\/\/businesshall\.ecej\.com\/[^?]*/wechatapp\/user\/code2Session(?:\?.*)?$ url script-response-body https://raw.githubusercontent.com/andlove/pic/refs/heads/master/ecej/EcejTokenCapture.js


^https:\/\/wechatapp\.ecej\.com\/livingpay\/v3\/xcx\/getBingCardListV2\.json(?:\?.*)?$ url script-request-body https://raw.githubusercontent.com/andlove/pic/refs/heads/master/ecej/EcejAppKeyCapture.js
^https:\/\/wechatapp\.ecej\.com\/livingpay\/v3\/xcx\/iot\/meterGasInfo\.json(?:\?.*)?$ url script-request-body https://raw.githubusercontent.com/andlove/pic/refs/heads/master/ecej/EcejAppKeyCapture.js
